let arr1 =["A",tryue,2];
console.log("\n********************************Length and index*******************\n");
console.log(arr1.length);
conlsoe.log(arr1[3]);
conlsoe.log(arr1[2]);
conlsoe.log(arr1[arr1.length-1]);
consloe.log("\n******************Length and index part2*************\n");
let arr3=Array(3);
arr3[2]="Adding a value!";
conlsoe.log(arr3[2]);
conlsoe.log(arr3[0]);
conlsoe.log(arr3[1]);
conlsoe.log(arr3[arr3.length-1]);
